import json

import requests

# The base URL of your GitLab instance
base_url = "https://gitlab.com"

# Your private token or personal token
private_token = "REDACTED"

# The ID of the project you want to add the webhook to
project_id = "59795263"

# The URL that the webhook will POST to
hook_url = "https://webhook-gitlab-et4qi4c73q-uc.a.run.app/webhook_gitlab"

# The headers for the API request
headers = {"PRIVATE-TOKEN": private_token, "Content-Type": "application/json"}

# The data for the webhook

data = {
    "name": "webhook_gitlab_gitalchemy",
    "description": "Webhook for GitLab events generated by gitalchemy",
    "url": hook_url,
    "push_events": True,
    "push_events_branch_filter": "",
    "issues_events": True,
    "confidential_issues_events": True,
    "merge_requests_events": True,
    "tag_push_events": True,
    "note_events": True,
    "confidential_note_events": True,
    "job_events": True,
    "pipeline_events": True,
    "wiki_page_events": True,
    "deployment_events": True,
    "releases_events": True,
    "enable_ssl_verification": True,
    "repository_update_events": True,
    "alert_status": "executable",
    "disabled_until": None,
    "url_variables": [],
    "created_at": "2012-10-12T17:04:47Z",
    "resource_access_token_events": True,
    "feature_flags_events": True,
    "emoji_events": True,
    "custom_webhook_template": '{"event":"{{object_kind}}"}',
    # "custom_headers": [{"key": "Authorization"}],
    # "push_events_branch_filter": "main",
    # "token": "secret-token",
}

# The API endpoint for creating a webhook
endpoint = f"{base_url}/api/v4/projects/{project_id}/hooks"

# Send the API request
response = requests.post(endpoint, headers=headers, data=json.dumps(data))

# Print the response
print(response.json())
