import json

import requests

url = "http://127.0.0.1:5001/gitalchemy/us-central1/webhook_gitlab"
# url = "https://webhook-gitlab-et4qi4c73q-uc.a.run.app/webhook_gitlab"

payload = {
    "object_kind": "merge_request",
    "event_type": "merge_request",
    "user": {
        "id": 22550624,
        "name": "Orest Pylypiak",
        "username": "opylypiak",
        "avatar_url": "https://secure.gravatar.com/avatar/6971b8cc42dc1311efe7119b2cd7d737ef7a70e7d1e2e7afd61f50839fc6f80b?s=80&d=identicon",
        "email": "[REDACTED]",
    },
    "project": {
        "id": 59853773,
        "name": "expo-gitlab-client",
        "description": None,
        "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        "namespace": "Thomas PEDOT",
        "visibility_level": 0,
        "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
        "default_branch": "main",
        "ci_config_path": "",
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
    },
    "object_attributes": {
        "assignee_id": None,
        "author_id": 22550624,
        "created_at": "2024-08-26 15:37:44 UTC",
        "description": "",
        "draft": False,
        "head_pipeline_id": None,
        "id": 323287213,
        "iid": 13,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "merge_commit_sha": None,
        "merge_error": None,
        "merge_params": {"force_remove_source_branch": "1"},
        "merge_status": "checking",
        "merge_user_id": None,
        "merge_when_pipeline_succeeds": False,
        "milestone_id": None,
        "source_branch": "feature/repository-view",
        "source_project_id": 59853773,
        "state_id": 1,
        "target_branch": "main",
        "target_project_id": 59853773,
        "time_estimate": 0,
        "title": "feature/repository view",
        "updated_at": "2024-08-26 15:37:48 UTC",
        "updated_by_id": None,
        "prepared_at": "2024-08-26 15:37:48 UTC",
        "assignee_ids": [],
        "blocking_discussions_resolved": True,
        "detailed_merge_status": "checking",
        "first_contribution": True,
        "human_time_change": None,
        "human_time_estimate": None,
        "human_total_time_spent": None,
        "labels": [],
        "last_commit": {
            "id": "ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "message": "add: issues\n",
            "title": "add: issues",
            "timestamp": "2024-08-26T18:36:10+03:00",
            "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/commit/ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "author": {"name": "opylypiak", "email": "[REDACTED]"},
        },
        "reviewer_ids": [],
        "source": {
            "id": 59853773,
            "name": "expo-gitlab-client",
            "description": None,
            "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
            "namespace": "Thomas PEDOT",
            "visibility_level": 0,
            "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        },
        "state": "opened",
        "target": {
            "id": 59853773,
            "name": "expo-gitlab-client",
            "description": None,
            "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
            "namespace": "Thomas PEDOT",
            "visibility_level": 0,
            "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        },
        "time_change": 0,
        "total_time_spent": 0,
        "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/merge_requests/13",
        "work_in_progress": False,
        "approval_rules": [],
        "action": "open",
    },
    "labels": [],
    "changes": {
        "merge_status": {"previous": "preparing", "current": "checking"},
        "updated_at": {
            "previous": "2024-08-26 15:37:44 UTC",
            "current": "2024-08-26 15:37:48 UTC",
        },
        "prepared_at": {"previous": None, "current": "2024-08-26 15:37:48 UTC"},
    },
    "repository": {
        "name": "expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "description": None,
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
    },
}

headers = {"Content-Type": "application/json"}

response = requests.post(url, data=json.dumps(payload), headers=headers)

print(response.status_code)
print(response.text)
