import json

import requests

url = "http://127.0.0.1:5001/gitalchemy/us-central1/webhook_gitlab"
# url = "https://webhook-gitlab-et4qi4c73q-uc.a.run.app/webhook_gitlab"

payload = {
    "object_kind": "note",
    "event_type": "note",
    "user": {
        "id": 11041577,
        "name": "Thomas PEDOT",
        "username": "thomas.pedot1",
        "avatar_url": "https://gitlab.com/uploads/-/system/user/avatar/11041577/avatar.png",
        "email": "[REDACTED]",
    },
    "project_id": 59853773,
    "project": {
        "id": 59853773,
        "name": "expo-gitlab-client",
        "description": None,
        "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        "namespace": "Thomas PEDOT",
        "visibility_level": 0,
        "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
        "default_branch": "main",
        "ci_config_path": "",
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
    },
    "object_attributes": {
        "attachment": None,
        "author_id": 11041577,
        "change_position": {
            "base_sha": None,
            "start_sha": None,
            "head_sha": None,
            "old_path": None,
            "new_path": None,
            "position_type": "text",
            "old_line": None,
            "new_line": None,
            "line_range": None,
        },
        "commit_id": None,
        "created_at": "2024-08-26 16:34:11 UTC",
        "discussion_id": "eaf23c0d7c8e4a139c436cbcbfd0d5233310caa5",
        "id": 2075754131,
        "line_code": "7030d0b2f71b999ff89a343de08c414af32fc93a_73_74",
        "note": "maybe in dev mode only ?",
        "noteable_id": 323287213,
        "noteable_type": "MergeRequest",
        "original_position": {
            "base_sha": "fa1ee3a4a8c1c4ab6f7ec33b9b513de90cc5f329",
            "start_sha": "fa1ee3a4a8c1c4ab6f7ec33b9b513de90cc5f329",
            "head_sha": "517ad66ec590b6b63e28c6c1d1bb913d00b863a5",
            "old_path": "package.json",
            "new_path": "package.json",
            "position_type": "text",
            "old_line": None,
            "new_line": 74,
            "line_range": {
                "start": {
                    "line_code": "7030d0b2f71b999ff89a343de08c414af32fc93a_73_74",
                    "type": "new",
                    "old_line": None,
                    "new_line": 74,
                },
                "end": {
                    "line_code": "7030d0b2f71b999ff89a343de08c414af32fc93a_73_74",
                    "type": "new",
                    "old_line": None,
                    "new_line": 74,
                },
            },
        },
        "position": {
            "base_sha": "fa1ee3a4a8c1c4ab6f7ec33b9b513de90cc5f329",
            "start_sha": "fa1ee3a4a8c1c4ab6f7ec33b9b513de90cc5f329",
            "head_sha": "ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "old_path": "package.json",
            "new_path": "package.json",
            "position_type": "text",
            "old_line": None,
            "new_line": 74,
            "line_range": {
                "start": {
                    "line_code": "7030d0b2f71b999ff89a343de08c414af32fc93a_73_74",
                    "type": "new",
                    "old_line": None,
                    "new_line": 74,
                },
                "end": {
                    "line_code": "7030d0b2f71b999ff89a343de08c414af32fc93a_73_74",
                    "type": "new",
                    "old_line": None,
                    "new_line": 74,
                },
            },
        },
        "project_id": 59853773,
        "resolved_at": None,
        "resolved_by_id": None,
        "resolved_by_push": None,
        "st_diff": None,
        "system": False,
        "type": "DiffNote",
        "updated_at": "2024-08-26 16:34:11 UTC",
        "updated_by_id": None,
        "description": "maybe in dev mode only ?",
        "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/merge_requests/13#note_2075754131",
        "action": "create",
    },
    "repository": {
        "name": "expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "description": None,
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
    },
    "merge_request": {
        "assignee_id": None,
        "author_id": 22550624,
        "created_at": "2024-08-26 15:37:44 UTC",
        "description": "",
        "draft": False,
        "head_pipeline_id": None,
        "id": 323287213,
        "iid": 13,
        "last_edited_at": None,
        "last_edited_by_id": None,
        "merge_commit_sha": None,
        "merge_error": None,
        "merge_params": {"force_remove_source_branch": "1"},
        "merge_status": "can_be_merged",
        "merge_user_id": None,
        "merge_when_pipeline_succeeds": False,
        "milestone_id": None,
        "source_branch": "feature/repository-view",
        "source_project_id": 59853773,
        "state_id": 1,
        "target_branch": "main",
        "target_project_id": 59853773,
        "time_estimate": 0,
        "title": "feature/repository view",
        "updated_at": "2024-08-26 16:34:11 UTC",
        "updated_by_id": None,
        "prepared_at": "2024-08-26 15:37:48 UTC",
        "assignee_ids": [],
        "blocking_discussions_resolved": True,
        "detailed_merge_status": "mergeable",
        "first_contribution": True,
        "human_time_change": None,
        "human_time_estimate": None,
        "human_total_time_spent": None,
        "labels": [],
        "last_commit": {
            "id": "ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "message": "add: issues\n",
            "title": "add: issues",
            "timestamp": "2024-08-26T18:36:10+03:00",
            "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/commit/ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "author": {"name": "opylypiak", "email": "[REDACTED]"},
        },
        "reviewer_ids": [],
        "source": {
            "id": 59853773,
            "name": "expo-gitlab-client",
            "description": None,
            "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
            "namespace": "Thomas PEDOT",
            "visibility_level": 0,
            "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        },
        "state": "opened",
        "target": {
            "id": 59853773,
            "name": "expo-gitlab-client",
            "description": None,
            "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "avatar_url": None,
            "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
            "namespace": "Thomas PEDOT",
            "visibility_level": 0,
            "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
            "default_branch": "main",
            "ci_config_path": "",
            "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
            "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
            "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        },
        "time_change": 0,
        "total_time_spent": 0,
        "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/merge_requests/13",
        "work_in_progress": False,
        "approval_rules": [],
    },
}

headers = {"Content-Type": "application/json"}

response = requests.post(url, data=json.dumps(payload), headers=headers)

print(response.status_code)
print(response.text)
