import json

import requests

url = "http://127.0.0.1:5001/gitalchemy/us-central1/webhook_gitlab"
# url = "https://webhook-gitlab-et4qi4c73q-uc.a.run.app/webhook_gitlab"

payload = {
    "object_kind": "tag_push",
    "event_name": "tag_push",
    "before": "39cc19165a882ad7941dd9dfd70084d44a5a144f",
    "after": "e1cf28d04aa218b927b6ebcb0d14408953a1bbcc",
    "ref": "refs/tags/v1.0.0",
    "ref_protected": False,
    "checkout_sha": "e19ad23aa32d08d98b94062f70bf5443e3f02527",
    "message": None,
    "user_id": 11041577,
    "user_name": "Thomas PEDOT",
    "user_username": "thomas.pedot1",
    "user_email": "",
    "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/11041577/avatar.png",
    "project_id": 59853773,
    "project": {
        "id": 59853773,
        "name": "expo-gitlab-client",
        "description": None,
        "web_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "avatar_url": None,
        "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        "namespace": "Thomas PEDOT",
        "visibility_level": 0,
        "path_with_namespace": "thomas.pedot1/expo-gitlab-client",
        "default_branch": "main",
        "ci_config_path": "",
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
    },
    "commits": [
        {
            "id": "e1cf28d04aa218b927b6ebcb0d14408953a1bbcc",
            "message": "Merge branch 'feature/repository-view' into 'main'\n\nfeature/repository view\n\nSee merge request thomas.pedot1/expo-gitlab-client!13",
            "title": "Merge branch 'feature/repository-view' into 'main'",
            "timestamp": "2024-08-26T16:40:04+00:00",
            "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/commit/e1cf28d04aa218b927b6ebcb0d14408953a1bbcc",
            "author": {"name": "Thomas PEDOT", "email": "[REDACTED]"},
            "added": [
                "ReactotronConfig.js",
                "app/workspace/projects/[projectId]/issues/list.tsx",
                "components/buttonList.tsx",
                "models/issuesList.tsx",
                "types/general.d.ts",
            ],
            "modified": [
                "app/(tabs)/home.tsx",
                "app/_layout.tsx",
                "app/workspace/issues/list.tsx",
                "app/workspace/projects/[projectId].tsx",
                "bun.lockb",
                "lib/gitlab/client.ts",
                "lib/utils.ts",
                "package.json",
            ],
            "removed": [],
        },
        {
            "id": "ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "message": "add: issues\n",
            "title": "add: issues",
            "timestamp": "2024-08-26T18:36:10+03:00",
            "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/commit/ce896ce83c7377401ed1c29f5238f0a280f7de59",
            "author": {"name": "opylypiak", "email": "[REDACTED]"},
            "added": ["models/issuesList.tsx", "types/general.d.ts"],
            "modified": [
                "app/(tabs)/home.tsx",
                "app/workspace/issues/list.tsx",
                "app/workspace/projects/[projectId].tsx",
                "app/workspace/projects/[projectId]/issues/list.tsx",
                "bun.lockb",
            ],
            "removed": [],
        },
        {
            "id": "39cc19165a882ad7941dd9dfd70084d44a5a144f",
            "message": "Merge remote-tracking branch 'origin' into feature/repository-view\n",
            "title": "Merge remote-tracking branch 'origin' into feature/repository-view",
            "timestamp": "2024-08-26T17:10:23+03:00",
            "url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client/-/commit/39cc19165a882ad7941dd9dfd70084d44a5a144f",
            "author": {"name": "opylypiak", "email": "[REDACTED]"},
            "added": [
                "app/workspace/notifications.tsx",
                "app/workspace/projects/[projectId]/issues/issue.json",
                "app/workspace/projects/[projectId]/issues/notes.json",
                "app/workspace/projects/[projectId]/issues/related_mr.json",
                "components/ui/checkbox.tsx",
                "components/ui/dropdown-menu.tsx",
                "components/ui/input.tsx",
                "components/ui/issue-status-icon.tsx",
                "components/ui/link-issue-section.tsx",
                "components/ui/skeleton.tsx",
                "firebase-functions/gitlab-events/.firebaserc",
                "firebase-functions/gitlab-events/.gitignore",
                "firebase-functions/gitlab-events/firebase.json",
                "firebase-functions/gitlab-events/functions/.gitignore",
                "firebase-functions/gitlab-events/functions/exemple_create_webhook.py",
                "firebase-functions/gitlab-events/functions/exemple_firebase.py",
                "firebase-functions/gitlab-events/functions/exemple_push_events.py",
                "firebase-functions/gitlab-events/functions/get_repos.py",
                "firebase-functions/gitlab-events/functions/gitalchemy-firebase-adminsdk-fnaju-289dccb9a0.json",
                "firebase-functions/gitlab-events/functions/gitlab_webhook_handlers.py",
                "firebase-functions/gitlab-events/functions/main.py",
                "firebase-functions/gitlab-events/functions/notifications.py",
                "firebase-functions/gitlab-events/functions/requirements.txt",
                "firebase-functions/gitlab-events/functions/utils.py",
            ],
            "modified": [
                ".env",
                ".gitignore",
                "README.md",
                "app.json",
                "app/(tabs)/home.tsx",
                "app/login.tsx",
                "app/templates/issue.tsx",
                "app/tree/[projectId].tsx",
                "app/tree/[projectId]/[fileId].tsx",
                "app/workspace/issues/[id].tsx",
                "app/workspace/issues/list.tsx",
                "app/workspace/projects/[projectId].tsx",
                "app/workspace/projects/[projectId]/issues/[issue_iid].tsx",
                "app/workspace/projects/list.tsx",
                "components/ui/issue-card.tsx",
                "components/ui/project-card.tsx",
                "lib/utils.ts",
                "package.json",
            ],
            "removed": [],
        },
    ],
    "total_commits_count": 3,
    "push_options": {},
    "repository": {
        "name": "expo-gitlab-client",
        "url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "description": None,
        "homepage": "https://gitlab.com/thomas.pedot1/expo-gitlab-client",
        "git_http_url": "https://gitlab.com/thomas.pedot1/expo-gitlab-client.git",
        "git_ssh_url": "git@gitlab.com:thomas.pedot1/expo-gitlab-client.git",
        "visibility_level": 0,
    },
}
headers = {"Content-Type": "application/json"}

response = requests.post(url, data=json.dumps(payload), headers=headers)

print(response.status_code)
print(response.text)
